/**
 * @file Express 4 adapter.
 *
 * Express is a **development dependency of this repository only**: nothing
 * here imports it at runtime *or at type level*. The interfaces below are the
 * minimum shape the adapter touches, declared locally, so the shipped `.d.ts`
 * mentions no package a consumer might not have — a consumer with
 * `skipLibCheck: false` and no `@types/express` typechecks against this file,
 * which is the claim CI proves with two separate tarball probes. Real Express
 * `Request`/`Response`/`RequestHandler` values are structurally assignable in
 * both directions, so nothing here needs a cast.
 *
 * ## The rule this file exists to enforce
 *
 * **A route with no declaration is never served, for any method.** Not for
 * `GET`, not for `HEAD`, not for `OPTIONS`. "Public" is a thing a route says
 * out loud — {@link ExpressAuth.allowPublic} — and never a thing that happens
 * because a lookup missed.
 *
 * The previous design got this wrong in a way worth recording, because the
 * shape is common. It offered a router-level `guard(resolve)` whose resolver
 * was handed `req.method` and `req.path`, and the README taught the resolver
 * body `table[`${method} ${path}`] ?? "none"`. Three things were then true at
 * once:
 *
 * - a **miss** was indistinguishable from a declaration of `"none"`, so after
 *   the safe methods were exempted from default-deny a miss on a `GET`, `HEAD`
 *   or `OPTIONS` was silent public access rather than a loud `500`;
 * - `req.path` inside a router mounted at a prefix is the path **after** the
 *   prefix (`/ships`, not `/api/ships`), so every key in a table written the
 *   obvious way missed;
 * - and even with the prefix right, the resolver was re-implementing Express's
 *   matcher by hand, so a trailing slash, a case-variant path and a
 *   parameterised route (`/ships/:id`) all missed too.
 *
 * A table lookup cannot be made equivalent to Express's matcher, so this
 * adapter does not try. **Declarations live at registration**, next to the
 * handler, where Express's own matcher binds them:
 *
 * ```ts
 * const api = secured(express.Router());
 * api.get("/ships", auth.requireSession(), listShips);
 * api.post("/ships/:id/navigate", auth.requireScope("fleet:control"), navigate);
 * api.get("/health", auth.allowPublic(), health);
 * app.use("/api/fleet/v1", api);
 * ```
 *
 * Whatever Express matched, it matched the declaration with it. Prefixes,
 * trailing slashes, case, parameters and `app.all` answering an `OPTIONS` are
 * all Express's business and stay Express's business.
 *
 * {@link secured} is the half that cannot be forgotten: it refuses **at
 * registration time** to register a handler that carries no declaration, so
 * the process does not start. An undeclared route cannot exist, rather than
 * being detected once a request finds it.
 *
 * ## The resolver that remains
 *
 * {@link ExpressAuth.guard} survives for routes this package cannot decorate —
 * fleet-service's routes are generated by tsoa, and there is no call site to
 * put a declaration in. Its resolver is **path-independent in practice**: a
 * `use`-mounted middleware runs before any route layer matches, so
 * `req.route` is `undefined` there and no honest path key exists. fleet's
 * resolver is a function of the method alone, which is exactly the shape that
 * is safe.
 *
 * A resolver that returns `undefined`, or throws, means **undeclared**: `500`,
 * on every method, before the header is read. It never falls back to `"none"`.
 *
 * **The guard trusts `req.method`.** Any method-override middleware must be
 * mounted *before* it, or a `POST` arrives here as whatever the override said.
 * This package ignores `X-HTTP-Method-Override` itself and always will.
 */

import { METHODS } from "node:http";

import type { Introspector } from "./center";
import type { Authorizer } from "./core";
import { createAuthorizer } from "./core";
import { MESSAGES } from "./messages";
import type {
  Decision,
  Identity,
  IntrospectionConfig,
  Kind,
  RouteRequirement,
} from "./types";

/**
 * The part of an Express `Request` this adapter reads. A real `Request`
 * satisfies it; declaring it locally keeps `express` out of the public types.
 *
 * Everything but `method` and `header` is optional so that a hand-made request
 * in a test, and a non-Express host, are assignable too. A real Express
 * `Request` has all of them.
 */
export interface RequestLike {
  /** The HTTP method, as the framework parsed it. Never an override header. */
  readonly method: string;
  /** Express's `req.path`: the path **after** any mount prefix, no query. */
  readonly path?: string;
  /**
   * Express's `req.baseUrl`: the prefix the containing router is mounted at,
   * or `""`. Given to a resolver so a diagnostic can name the whole path;
   * `baseUrl + path` is not a route key, because it is still not what
   * Express matched on.
   */
  readonly baseUrl?: string;
  /** Express's `req.originalUrl`: the URL as received, query string included. */
  readonly originalUrl?: string;
  /**
   * The route Express matched, when one has matched **yet**. A middleware
   * mounted with `use` runs before any route layer, so this is `undefined`
   * there — which is the whole reason a `use`-mounted resolver cannot key on
   * a path. It is populated for a handler attached to a route, where
   * `route.path` is the *pattern* (`"/ships/:id"`), not the request's path.
   */
  readonly route?: { readonly path?: string } | undefined;
  /**
   * One request header, case-insensitively. Express returns the joined value
   * for a repeated header and an array only for `set-cookie`; both shapes are
   * accepted here so a real `Request` is assignable without a cast.
   */
  header(name: string): string | string[] | undefined;
}

/** The part of an Express `Response` this adapter writes. */
export interface ResponseLike {
  locals: Record<string, unknown>;
  status(code: number): ResponseLike;
  json(body: unknown): unknown;
}

/** Express's `next`. An error argument makes Express fail the request. */
export type NextLike = (err?: unknown) => void;

/** Structurally an Express `RequestHandler`, without naming one. */
export type HandlerLike = (
  req: RequestLike,
  res: ResponseLike,
  next: NextLike
) => void;

/** `res.locals` key holding the verified identity, or null for a visitor. */
export const LOCALS_IDENTITY = "identity";
/** `res.locals` key holding the subject — automation-service's `detail.actor`. */
export const LOCALS_ACTOR = "actor";
/** `res.locals` key holding what the route declared, or null if it declared nothing. */
export const LOCALS_REQUIRES = "authRequires";

/**
 * The verified identity for this request, or null when the caller is a
 * visitor. This and {@link kindOf} / {@link actorOf} / {@link hasScope} are
 * the **only** supported accessors.
 *
 * There is deliberately no `res.locals.kind`. It existed and was removed: a
 * second copy of the center's answer is a second thing to keep true, and the
 * one failure this package exists to prevent is a service deriving `kind`
 * itself. One source of truth — `res.locals.identity` — and `kindOf()` reads
 * it.
 */
export const identityOf = (res: ResponseLike): Identity | null =>
  (res.locals[LOCALS_IDENTITY] as Identity | null | undefined) ?? null;

/** The subject, or null for a visitor. */
export const actorOf = (res: ResponseLike): string | null =>
  identityOf(res)?.sub ?? null;

/**
 * The center's `kind`, or null for a visitor. Never derived from the subject:
 * a fence written as `kindOf(res) === "machine"` is the supported spelling.
 */
export const kindOf = (res: ResponseLike): Kind | null =>
  identityOf(res)?.kind ?? null;

/** True when this request carries a verified session holding `scope`. */
export const hasScope = (res: ResponseLike, scope: string): boolean =>
  identityOf(res)?.scopes.includes(scope) ?? false;

/**
 * Maps a request to what its route declares.
 *
 * Returning `undefined` means **undeclared**, which is a `500` on every
 * method. It is not `"none"`, and there is deliberately no way to spell "I
 * could not find this route, serve it anyway".
 */
export type RequirementResolver = (
  req: RequestLike
) => RouteRequirement | undefined;

// ---------------------------------------------------------------------------
// The registry
// ---------------------------------------------------------------------------

/*
 * What a handler is, recorded outside the handler.
 *
 * WeakMaps rather than a property on the function, so nothing this package is
 * handed is mutated — a frozen middleware, or one shared with another library,
 * is none of our business. These are module-scoped, which assumes one copy of
 * this package per process. That is true for the three consumers (each
 * installs one tarball) and, if it ever stopped being true, `secured()` would
 * not recognise the other copy's declarations and would refuse to start with
 * the message below — the loudest possible way for that to surface.
 */

/** Handlers that carry a route declaration, and what they declare. */
const declarations = new WeakMap<object, RouteRequirement>();
/** Router-level guards: a blanket declaration for everything behind them. */
const guards = new WeakSet<object>();
/** Handlers a caller has explicitly vouched for as not being a route. */
const passthroughs = new WeakSet<object>();
/** Routers and apps already wrapped by {@link secured}. */
const securedTargets = new WeakSet<object>();

/** What a declared handler declares, or undefined if it declares nothing. */
export const declarationOf = (
  handler: unknown
): RouteRequirement | undefined =>
  typeof handler === "function" ? declarations.get(handler) : undefined;

/**
 * Vouch for a handler that is **not a route**: a body parser, a CORS
 * middleware, a logger — anything that will call `next()` rather than answer.
 *
 * {@link secured} refuses a `use()` of an undeclared handler, because from the
 * outside a middleware and a route are the same shape and it cannot tell which
 * one will answer. This is the explicit way to say which it is, and `why` is
 * required so the escape hatch reads as a decision in the diff rather than as
 * a cast.
 *
 * ```ts
 * api.use(passthrough(express.json(), "parses bodies; never answers"));
 * ```
 *
 * The handler is returned unchanged, so arity — which is how Express tells an
 * error handler from an ordinary one — is preserved exactly.
 */
export function passthrough<H>(handler: H, why: string): H {
  if (typeof handler !== "function") {
    throw new TypeError("passthrough() takes a middleware function");
  }
  if (typeof why !== "string" || why.trim().length === 0) {
    throw new TypeError(
      "passthrough() requires a reason: say why this handler is not a route that needs a declaration"
    );
  }
  passthroughs.add(handler);
  return handler;
}

// ---------------------------------------------------------------------------
// secured()
// ---------------------------------------------------------------------------

/**
 * Every method name Express can register a route under.
 *
 * Taken from Node's own list — which is where Express's `methods` dependency
 * gets it too — rather than from a hand-written set of the seven anybody
 * remembers. A hand-written set is a hole shaped like `router.trace(...)`.
 */
const ROUTE_METHODS: readonly string[] = [
  ...new Set([...METHODS.map((m) => m.toLowerCase()), "delete", "all"]),
];

const PLEASE_DECLARE = [
  "Every route must say what it needs, at the point it is registered:",
  "",
  "    auth.allowPublic()                 — anyone, including an anonymous visitor",
  "    auth.requireSession()              — any verified session",
  '    auth.requireScope("fleet:control") — a session carrying that scope',
  "",
  "If this handler is middleware rather than a route — a body parser, CORS, a",
  "logger — wrap it: passthrough(handler, \"why it never answers\").",
].join("\n");

const flattenHandlers = (values: readonly unknown[]): unknown[] => {
  const out: unknown[] = [];
  for (const value of values) {
    if (Array.isArray(value)) out.push(...flattenHandlers(value));
    else out.push(value);
  }
  return out;
};

/** The leading path/pattern arguments Express accepts, which are not handlers. */
const isPathArgument = (value: unknown): boolean =>
  typeof value === "string" ||
  value instanceof RegExp ||
  (Array.isArray(value) && value.every(isPathArgument));

const describePath = (value: unknown): string =>
  isPathArgument(value) ? String(value) : "<no path>";

/**
 * Refuse, at startup, to register a route with no declaration.
 *
 * `label` is the method the call came in on, used only in the message. The
 * throw is deliberately an `Error` at require/boot time: a service that cannot
 * say what one of its routes needs must not start, because the alternative is
 * that it starts and serves it.
 */
const assertRouteDeclared = (
  label: string,
  args: readonly unknown[],
  name: string
): void => {
  const handlers = flattenHandlers(args).filter((a) => !isPathArgument(a));
  const declared = handlers.some(
    (h) =>
      typeof h === "function" && (declarations.has(h) || guards.has(h))
  );
  if (declared) return;

  throw new Error(
    `${name}.${label}(${describePath(args[0])}) was registered without an authorization declaration.\n\n` +
      PLEASE_DECLARE
  );
};

/**
 * The same, for `use()`. A `use` may legitimately mount things that are not
 * routes, so it accepts more: a declaration, a router-level guard, another
 * secured router, an explicitly vouched-for passthrough, or an error handler
 * (arity 4 — Express only ever calls it with an error in hand, so it cannot
 * be the thing that serves an undeclared route).
 */
const assertUseSafe = (args: readonly unknown[], name: string): void => {
  const mounted = flattenHandlers(args).filter((a) => !isPathArgument(a));
  for (const item of mounted) {
    if (typeof item === "function") {
      if (declarations.has(item)) continue;
      if (guards.has(item)) continue;
      if (passthroughs.has(item)) continue;
      if (securedTargets.has(item)) continue; // an express.Router() is a function
      if (item.length >= 4) continue; // an error handler
    } else if (typeof item === "object" && item !== null && securedTargets.has(item)) {
      continue;
    }

    throw new Error(
      `${name}.use(${describePath(args[0])}) was given a handler that is neither a declaration nor a vouched-for middleware.\n\n` +
        PLEASE_DECLARE +
        "\n\nA nested router is fine too, as long as it is itself secured():\n" +
        "\n    api.use(\"/ships\", secured(express.Router()));\n"
    );
  }
};

/**
 * Make an Express router or app refuse, **at registration time**, to register
 * a handler that carries no authorization declaration.
 *
 * ```ts
 * const api = secured(express.Router());
 * api.get("/ships", auth.requireSession(), listShips);   // fine
 * api.get("/ships", listShips);                          // throws at startup
 * ```
 *
 * This is the backstop that cannot be forgotten, and it is a *startup* failure
 * rather than a per-request one: an undeclared route does not exist, instead
 * of existing and being caught the first time somebody asks for it. A
 * per-request default-deny can only ever be as good as the code path that
 * notices; this one is as good as the process starting.
 *
 * The target is patched in place and returned, so `app.use("/api", api)`,
 * nesting and everything else about it are unchanged. Calling it twice on the
 * same target does nothing the second time.
 *
 * **What it does not cover**, stated because a fence whose gaps are unknown is
 * worse than no fence:
 *
 * - handlers registered on the *app* rather than on a secured router;
 * - handlers registered through a reference to the raw router captured before
 *   `secured()` was called;
 * - anything mounted *before* the secured router in the middleware chain,
 *   which answers without ever reaching it;
 * - what a `passthrough()` actually does, which is the caller's word.
 */
export function secured<T extends object>(target: T): T {
  if (securedTargets.has(target)) return target;
  securedTargets.add(target);

  const record = target as unknown as Record<string, unknown>;
  const name =
    typeof record["name"] === "string" && record["name"].length > 0
      ? (record["name"] as string)
      : "router";

  for (const method of ROUTE_METHODS) {
    const original = record[method];
    if (typeof original !== "function") continue;
    const call = original.bind(target) as (...args: unknown[]) => unknown;
    record[method] = (...args: unknown[]): unknown => {
      // `app.get("view engine")` is Express's settings GETTER, not a route.
      // One string argument and nothing else is unambiguously that: a route
      // with a path and no handler at all is not a route either.
      if (method === "get" && args.length === 1 && typeof args[0] === "string") {
        return call(...args);
      }
      assertRouteDeclared(method, args, name);
      return call(...args);
    };
  }

  const originalUse = record["use"];
  if (typeof originalUse === "function") {
    const call = originalUse.bind(target) as (...args: unknown[]) => unknown;
    record["use"] = (...args: unknown[]): unknown => {
      assertUseSafe(args, name);
      return call(...args);
    };
  }

  // `router.route("/x").get(handler)` registers a route without going through
  // `router.get`, so the returned IRoute is secured too — otherwise it is a
  // hole in the shape of a chaining style somebody prefers.
  const originalRoute = record["route"];
  if (typeof originalRoute === "function") {
    const call = originalRoute.bind(target) as (...args: unknown[]) => unknown;
    record["route"] = (...args: unknown[]): unknown => {
      const route = call(...args);
      return typeof route === "object" && route !== null
        ? secured(route as object)
        : route;
    };
  }

  return target;
}

export interface ExpressAuth {
  /**
   * Declare what a route needs, and enforce it. Attach it to the route:
   *
   * ```ts
   * api.post("/ships/:id/navigate", auth.requires("fleet:control"), navigate);
   * ```
   *
   * Express's own matcher binds this to the same route it binds the handler
   * to, so a mount prefix, a trailing slash, a case-variant path and a
   * parameter all resolve exactly as the route does — and a `HEAD` reaches the
   * `GET` route's declaration because Express dispatches it to that route.
   */
  requires(requires: RouteRequirement): HandlerLike;
  /** `requires(scope)`, spelled the way the services that exist today spell it. */
  requireScope(scope: string): HandlerLike;
  /** Any verified session, carrying any scopes at all, including none. */
  requireSession(): HandlerLike;
  /**
   * Declare a route **public**: an anonymous caller proceeds as a visitor on a
   * safe method, and a mutating method answers `500`, because a mutation that
   * needs no credential is a defect rather than a policy.
   *
   * This is the only way a route is public. A declaration nobody wrote is not
   * a public route, it is an undeclared one.
   */
  allowPublic(): HandlerLike;
  /**
   * Router-level middleware, for routes that cannot carry a declaration —
   * generated routers, chiefly. Mount once with `router.use(auth.guard(...))`.
   *
   * `resolve` is a fixed requirement or a function of the request. Returning
   * `undefined`, or throwing, means **undeclared**: `500` on every method,
   * before the header is read. There is no fallback to `"none"`.
   *
   * The request handed to `resolve` carries `method`, `path`, `baseUrl`,
   * `originalUrl` and `header()`. It does **not** carry a matched `route`: a
   * `use`-mounted middleware runs before any route layer matches, which is
   * precisely why a resolver must not key on a path it reconstructs itself.
   * Key on the method, or use per-route declarations.
   *
   * On a `HEAD`, `resolve` is called with `method` reading `"GET"`, because
   * `HEAD /x` is the same route as `GET /x` and Express dispatches it to that
   * handler. The real `req.method` is not touched.
   */
  guard(resolve: RouteRequirement | RequirementResolver): HandlerLike;
}

/** Writes a rejection in the family's `{"error":{"message":…}}` envelope. */
const sendRejection = (
  res: ResponseLike,
  status: number,
  message: string
): void => {
  res.status(status).json({ error: { message } });
};

const apply = (res: ResponseLike, decision: Decision, next: NextLike): void => {
  if (decision.outcome === "reject") {
    sendRejection(res, decision.status, decision.message);
    return;
  }
  res.locals[LOCALS_IDENTITY] = decision.identity;
  res.locals[LOCALS_ACTOR] = decision.identity?.sub ?? null;
  next();
};

/**
 * The same request, reading `GET` as its method.
 *
 * Only for handing to a {@link RequirementResolver}: `HEAD /x` is routed to
 * the `GET /x` handler by Express, so what `GET /x` declared is what governs
 * it. Nothing is mutated — the real `req.method` the handlers and the policy
 * see is untouched, so a `HEAD` is still answered as a `HEAD`.
 */
const asGet = (req: RequestLike): RequestLike =>
  new Proxy(req, {
    get(target, property) {
      if (property === "method") return "GET";
      const value = Reflect.get(target, property, target) as unknown;
      // Bound to the real request: Express's `path`/`header` read internals
      // that a proxy receiver would not satisfy.
      return typeof value === "function" ? value.bind(target) : value;
    },
  }) as RequestLike;

export function createExpressAuth(
  source: IntrospectionConfig | Introspector | Authorizer
): ExpressAuth {
  const authorizer: Authorizer =
    "authorize" in source ? source : createAuthorizer(source);

  const handlerFor = (resolve: RequirementResolver): HandlerLike => {
    return (req, res, next) => {
      let requires: RouteRequirement | undefined;
      try {
        requires =
          req.method.toUpperCase() === "HEAD" ? resolve(asGet(req)) : resolve(req);
      } catch {
        requires = undefined;
      }

      if (requires === undefined) {
        // Undeclared. A resolver that threw has told us nothing about this
        // route; a resolver that returned `undefined` has told us it could
        // not find it. Both are the same class of defect — ours — and both
        // fail closed on EVERY method, safe ones included.
        //
        // The alternative, and the bug this replaced: falling back to `"none"`
        // makes a miss indistinguishable from a route that declared itself
        // public, so after the safe methods were exempted from default-deny a
        // missed `GET`, `HEAD` or `OPTIONS` was served anonymously and in
        // silence. `"session"` would be no better — it serves the route to
        // anyone holding any token at all. Neither is a thing to guess.
        res.locals[LOCALS_REQUIRES] = null;
        sendRejection(res, 500, MESSAGES.undeclaredRoute);
        return;
      }
      res.locals[LOCALS_REQUIRES] = requires;

      authorizer
        .authorize({
          method: req.method,
          requires,
          // A repeated header arrives joined; `bearerFrom` reads that as no
          // credential rather than picking one of the two.
          authorization: headerValue(req, "Authorization"),
        })
        .then((decision) => apply(res, decision, next))
        // The authorizer is written not to reject; if a host's injected
        // introspector does, the request must still fail closed rather than
        // hand Express an unhandled promise. `next(err)` and not `next()`:
        // passing no error would run the handler the guard just failed to
        // authorize.
        .catch(() => next(new Error("introspection failed")));
    };
  };

  /** A handler that declares `requires`, tagged so `secured()` can see it. */
  const declaring = (requires: RouteRequirement): HandlerLike => {
    const handler = handlerFor(() => requires);
    declarations.set(handler, requires);
    return handler;
  };

  return {
    requires: declaring,
    requireScope: declaring,
    requireSession: () => declaring("session"),
    allowPublic: () => declaring("none"),
    guard: (resolve) => {
      const handler = handlerFor(
        typeof resolve === "function" ? resolve : () => resolve
      );
      guards.add(handler);
      return handler;
    },
  };
}

/** One header as a single string, or null. An array is joined as Node joins. */
const headerValue = (req: RequestLike, name: string): string | null => {
  const value = req.header(name);
  if (value === undefined) return null;
  return Array.isArray(value) ? value.join(", ") : value;
};
